// Generated by tools/generate_web_contracts.py; edit the Python contracts.
export interface ActiveShipmentPayload {
  contract: PublicContractPayload;
  origin_system_id: number;
  destination_system_id: number;
  origin_system_name: string;
  destination_system_name: string;
  deadline: string;
  picked: boolean;
}

export interface ArtifactsPayload {
  snapshot: boolean;
  plan: boolean;
  execution: boolean;
}

export interface BoundStrengthening {
  system_relaxation_status: string | null;
  system_relaxation_bound_units: number | null;
  system_relaxation_bound_isk: string | null;
  system_relaxation_wall_time_seconds: number;
  system_relaxation_systems: number;
  incompatibility_pairs: number;
  incompatibility_cliques: number;
  decomposition_status: string | null;
  decomposition_iterations: number;
  decomposition_learned_cuts: number;
  decomposition_subproblem_wall_time_seconds: number;
  decomposition_proof_closed: boolean;
}

export interface CancelledJob {
  id: string;
  operation: "scan" | "rank" | "solve" | "replan";
  progress: string;
  elapsed_seconds: number;
  status: "cancelled";
}

export interface CertificatePayload {
  status: "proven_optimal" | "proven_infeasible" | "feasible_not_proven" | "unknown";
  solver_status: string;
  objective_units: number | null;
  objective_isk: string | null;
  best_bound_units: number | null;
  best_bound_isk: string | null;
  absolute_gap_units: number | null;
  relative_gap: number | null;
  problem_sha256: string;
  solver_name: string;
  solver_version: string;
  wall_time_seconds: number;
  branches: number;
  conflicts: number;
  scope_untruncated: boolean;
  feasibility_verified: boolean;
  independent_reference_verified: boolean;
  bound_strengthening: BoundStrengthening;
  claim: string;
}

export interface CompletedJob {
  id: string;
  operation: "scan" | "rank" | "solve" | "replan";
  progress: string;
  elapsed_seconds: number;
  status: "completed";
  result: ScanResponse | PlanResponse | RankResponse;
}

export interface ExecutionPayload {
  schema_version: 3;
  current_time: string;
  session_deadline: string;
  current_system_id: number;
  cargo_capacity_units: number;
  collateral_budget_units: number;
  collateral_mode: "locked" | "rolling";
  terminal_system_id: number | null;
  remaining_required_system_ids: Array<number>;
  max_simultaneous_contracts: number | null;
  travel: TravelPayload;
  security: ExecutionSecurity;
  completed_contract_ids: Array<number>;
  active_shipments: Array<ActiveShipmentPayload>;
  current_system_name: string | null;
  active_count: number;
  completed_count: number;
  cargo_in_use_m3: string;
  collateral_locked_isk: string;
  terminal_system_name: string | null;
  remaining_required_systems: Array<RequiredSystemPayload>;
  can_end_safely: boolean;
  horizon_expired: boolean;
}

export interface ExecutionResponse {
  revision: number;
  proposal_id: string | null;
  execution: ExecutionPayload | null;
  plan?: PlanPayload | null;
}

export interface ExecutionSecurity {
  minimum_security: number | null;
  avoided_system_ids: Array<number>;
  allowed_bands: Array<string> | null;
  gank_avoided_system_ids: Array<number>;
  gank_ship_kill_threshold: number | null;
  gank_activity_fetched_at: string | null;
  threat_avoided_system_ids: Array<number>;
  threat_categories: Array<string>;
  threat_min_events: number | null;
  threat_intel_fetched_at: string | null;
  threat_window_seconds: number | null;
  threat_gate_radius_m: number | null;
  threat_coverage_region_ids: Array<number>;
  threat_incomplete_region_ids: Array<number>;
}

export interface FailedJob {
  id: string;
  operation: "scan" | "rank" | "solve" | "replan";
  progress: string;
  elapsed_seconds: number;
  status: "failed";
  error: string;
}

export interface JobEnvelope {
  job: RunningJob | CompletedJob | FailedJob | CancelledJob;
}

export interface NamedSystem {
  id: number;
  name: string;
}

export interface PathSystem {
  system_id: number;
  name: string;
  security_status: number | null;
  security_band: string | null;
}

export interface PlanModel {
  start_system_id: number;
  cargo_capacity_m3: string;
  collateral_budget_isk: string;
  horizon_seconds: number;
  snapshot_time: string;
  collateral_mode: "locked" | "rolling";
  return_to_start: boolean;
  required_system_ids: Array<number>;
  finish_system_id: number | null;
  terminal_system_id: number | null;
  max_simultaneous_contracts: number | null;
  seconds_per_jump: number;
  service_seconds: number;
  minimum_security: number | null;
  allowed_security_bands: Array<string> | null;
  avoided_system_ids: Array<number>;
  gank_avoided_system_ids: Array<number>;
  gank_ship_kill_threshold: number | null;
  gank_activity_fetched_at: string | null;
  threat_avoided_system_ids: Array<number>;
  threat_categories: Array<string>;
  threat_min_events: number | null;
  threat_intel_fetched_at: string | null;
  threat_window_seconds: number | null;
  threat_gate_radius_m: number | null;
  threat_coverage_region_ids: Array<number>;
  threat_incomplete_region_ids: Array<number>;
  start_system_name?: string | null;
  finish_system_name?: string | null;
  avoided_systems?: Array<NamedSystem>;
  required_systems?: Array<NamedSystem>;
}

export interface PlanPayload {
  schema_version: 3;
  summary: PlanSummary;
  certificate: CertificatePayload;
  scope: PlanScope;
  model: PlanModel;
  route: Array<RouteStepPayload>;
  travel_legs: Array<TravelLegPayload>;
}

export interface PlanResponse {
  revision: number;
  proposal_id: string | null;
  snapshot: SnapshotSummary | null;
  plan: PlanPayload;
  execution: ExecutionPayload | null;
}

export interface PlanScope {
  snapshot_fetched_at: string;
  snapshot_compatibility_date: string;
  sde_build_number: number;
  scanned_region_ids: Array<number>;
  public_couriers_seen: number;
  eligible_contracts: number;
  policy_exclusions: Record<string, number>;
  safe_reductions: Record<string, number>;
  heuristic_reductions: Record<string, number>;
}

export interface PlanSummary {
  selected_contract_ids: Array<number>;
  total_reward_units: number;
  total_reward_isk: string;
  finish_seconds: number | null;
}

export interface PublicContractPayload {
  contract_id: number;
  origin_location_id: number;
  destination_location_id: number;
  volume_units: number;
  collateral_units: number;
  reward_units: number;
  date_expired: string;
  days_to_complete: number;
  title: string;
  date_issued: string | null;
}

export interface RankItem {
  contract_id: number;
  title: string;
  origin: string;
  destination: string;
  reward_isk: string;
  volume_m3: string;
  collateral_isk: string;
  solo_jumps: number;
  solo_seconds: number;
  reward_per_hour_isk: number | null;
  reward_per_jump_isk: number | null;
  reward_to_collateral: number | null;
}

export interface RankResponse {
  revision: number;
  proposal_id: string | null;
  scope: RankScope;
  items: Array<RankItem>;
}

export interface RankScope {
  public_couriers_seen: number;
  eligible_contracts: number;
  policy_exclusions: Record<string, number>;
  safe_reductions: Record<string, number>;
  heuristic_reductions: Record<string, number>;
  scope_untruncated: boolean;
}

export interface RankingPayload {
  scope: RankScope;
  items: Array<RankItem>;
}

export interface RequiredSystemPayload {
  system_id: number;
  name: string;
}

export interface RouteStepPayload {
  sequence: number;
  action: "pickup" | "delivery";
  contract_id: number;
  system_id: number;
  location_id: number;
  arrival_seconds: number;
  completion_seconds: number;
  cargo_after_units: number;
  cargo_after_m3: string;
  collateral_after_units: number;
  collateral_after_isk: string;
  cumulative_reward_units: number;
  cumulative_reward_isk: string;
  jump_path: Array<number>;
  system_name?: string | null;
  jump_count?: number;
  jump_path_systems?: Array<PathSystem>;
  title?: string;
  reward_isk?: string;
  volume_m3?: string;
  mandatory?: boolean;
}

export interface RunningJob {
  id: string;
  operation: "scan" | "rank" | "solve" | "replan";
  progress: string;
  elapsed_seconds: number;
  status: "running";
}

export interface ScanResponse {
  revision: number;
  proposal_id: string | null;
  snapshot: SnapshotSummary | null;
}

export interface SdeSummary {
  build_number: number;
  release_date: string;
  systems: number;
  regions: number;
  empire_regions: number;
  npc_stations: number;
}

export interface SnapshotSummary {
  fetched_at: string;
  age_seconds: number;
  compatibility_date: string;
  sde_build_number: number;
  region_ids: Array<number>;
  region_names: Array<string>;
  contracts: number;
  system_kills_fetched_at: string | null;
  system_kill_systems: number;
  threat_intel_fetched_at: string | null;
  threat_window_seconds: number | null;
  threat_gate_radius_m: number | null;
  threat_coverage_region_ids: Array<number>;
  threat_incomplete_region_ids: Array<number>;
  threat_killmails_seen: number;
  gate_threat_events: number;
}

export interface StatusWithJob {
  revision: number;
  proposal_id: string | null;
  app_version: string;
  warnings: Array<string>;
  snapshot_requires_refresh: boolean;
  sde: SdeSummary;
  snapshot: SnapshotSummary | null;
  plan: PlanPayload | null;
  execution: ExecutionPayload | null;
  plan_armable: boolean;
  artifacts: ArtifactsPayload;
  job: RunningJob | CompletedJob | FailedJob | CancelledJob | null;
}

export interface Suggestion {
  id: number;
  name: string;
  security_status?: number;
}

export interface Suggestions {
  items: Array<Suggestion>;
}

export interface TravelLegPayload {
  sequence: number;
  kind: "pickup" | "delivery" | "waypoint" | "finish";
  from_system_id: number;
  to_system_id: number;
  arrival_seconds: number;
  completion_seconds: number;
  contract_id: number | null;
  jump_path: Array<number>;
  from_system_name?: string | null;
  to_system_name?: string | null;
  jump_count?: number;
  jump_path_systems?: Array<PathSystem>;
}

export interface TravelPayload {
  seconds_per_jump: number;
  service_seconds: number;
}

export interface ContractTypes {
  ActiveShipmentPayload: ActiveShipmentPayload;
  ArtifactsPayload: ArtifactsPayload;
  BoundStrengthening: BoundStrengthening;
  CancelledJob: CancelledJob;
  CertificatePayload: CertificatePayload;
  CompletedJob: CompletedJob;
  ExecutionPayload: ExecutionPayload;
  ExecutionResponse: ExecutionResponse;
  ExecutionSecurity: ExecutionSecurity;
  FailedJob: FailedJob;
  JobEnvelope: JobEnvelope;
  NamedSystem: NamedSystem;
  PathSystem: PathSystem;
  PlanModel: PlanModel;
  PlanPayload: PlanPayload;
  PlanResponse: PlanResponse;
  PlanScope: PlanScope;
  PlanSummary: PlanSummary;
  PublicContractPayload: PublicContractPayload;
  RankItem: RankItem;
  RankResponse: RankResponse;
  RankScope: RankScope;
  RankingPayload: RankingPayload;
  RequiredSystemPayload: RequiredSystemPayload;
  RouteStepPayload: RouteStepPayload;
  RunningJob: RunningJob;
  ScanResponse: ScanResponse;
  SdeSummary: SdeSummary;
  SnapshotSummary: SnapshotSummary;
  StatusWithJob: StatusWithJob;
  Suggestion: Suggestion;
  Suggestions: Suggestions;
  TravelLegPayload: TravelLegPayload;
  TravelPayload: TravelPayload;
}

export type Schema = {ref: keyof ContractTypes} | {union: Schema[]} |
  {literal: unknown[]} | {object: Record<string, Schema>; required: string[]} |
  {array: Schema} | {values: Schema} |
  {type: "integer" | "number" | "string" | "boolean" | "null"};
