"""Generate browser declarations and runtime schemas from the Python response contracts."""

from __future__ import annotations

import argparse
import json
import types
from html.parser import HTMLParser
from pathlib import Path
from typing import Literal, NotRequired, Union, cast, get_args, get_origin, is_typeddict

from eve_courier_optimizer.application.plan_contract import PlanPayload, contract_fields
from eve_courier_optimizer.web.contracts import (
    ExecutionResponse,
    JobEnvelope,
    PlanResponse,
    RankingPayload,
    RankResponse,
    ScanResponse,
    StatusWithJob,
    Suggestions,
)

ASSETS = Path(__file__).resolve().parents[1] / "src/eve_courier_optimizer/web/assets"
ROOTS = (
    RankingPayload,
    PlanPayload,
    StatusWithJob,
    JobEnvelope,
    Suggestions,
    ScanResponse,
    PlanResponse,
    RankResponse,
    ExecutionResponse,
)


class ElementIds(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.elements: dict[str, str] = {}

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        identifier = dict(attrs).get("id")
        if identifier is not None:
            self.elements[identifier] = tag


def dom_declarations() -> str:
    parser = ElementIds()
    parser.feed((ASSETS / "index.html").read_text(encoding="utf-8"))
    return "// Generated from index.html by tools/generate_web_contracts.py.\n" + (
        "export interface ElementIds {\n"
        + "\n".join(
            f'  "#{key}": HTMLElementTagNameMap["{tag}"];'
            for key, tag in sorted(parser.elements.items())
        )
        + "\n}\n"
    )


def generate() -> tuple[str, str]:
    declarations: dict[str, str] = {}
    schemas: dict[str, object] = {}

    def describe(annotation: object) -> tuple[str, object]:
        origin = get_origin(annotation)
        args = cast(tuple[object, ...], get_args(annotation))
        if origin is NotRequired:
            return describe(args[0])
        if origin in (Union, types.UnionType):
            parts = [describe(arg) for arg in args]
            return " | ".join(part[0] for part in parts), {"union": [p[1] for p in parts]}
        if origin is Literal:
            return " | ".join(json.dumps(arg) for arg in args), {"literal": args}
        if is_typeddict(annotation):
            name = cast(type[object], annotation).__name__
            if name not in declarations:
                fields = contract_fields(annotation)
                lines: list[str] = []
                properties: dict[str, object] = {}
                required: list[str] = []
                for key, field in fields.items():
                    field_type, schema = describe(field)
                    optional = get_origin(field) is NotRequired
                    lines.append(f"  {key}{'?' if optional else ''}: {field_type};")
                    properties[key] = schema
                    if not optional:
                        required.append(key)
                declarations[name] = f"export interface {name} {{\n" + "\n".join(lines) + "\n}"
                schemas[name] = {"object": properties, "required": required}
            return name, {"ref": name}
        if origin is list:
            element, schema = describe(args[0])
            return f"Array<{element}>", {"array": schema}
        if origin is dict and args[0] is str:
            element, schema = describe(args[1])
            return f"Record<string, {element}>", {"values": schema}
        primitives = {
            int: ("number", "integer"),
            float: ("number", "number"),
            str: ("string", "string"),
            bool: ("boolean", "boolean"),
            type(None): ("null", "null"),
        }
        if not isinstance(annotation, type) or annotation not in primitives:
            raise TypeError(f"unsupported browser contract: {annotation!r}")
        name, primitive = primitives[annotation]
        return name, {"type": primitive}

    for root in ROOTS:
        describe(root)
    banner = "// Generated by tools/generate_web_contracts.py; edit the Python contracts.\n"
    names = sorted(declarations)
    declarations_text = banner + "\n\n".join(declarations[name] for name in names)
    declarations_text += (
        "\n\nexport interface ContractTypes {\n"
        + "\n".join(f"  {name}: {name};" for name in names)
        + "\n}\n"
    )
    declarations_text += """
export type Schema = {ref: keyof ContractTypes} | {union: Schema[]} |
  {literal: unknown[]} | {object: Record<string, Schema>; required: string[]} |
  {array: Schema} | {values: Schema} |
  {type: "integer" | "number" | "string" | "boolean" | "null"};
"""
    schema_text = (
        banner
        + """/**
 * @type {Record<keyof import("./contracts").ContractTypes, import("./contracts").Schema>}
 */
export const schemas = """
        + json.dumps(schemas, indent=2, sort_keys=True)
        + ";\n"
    )
    return declarations_text, schema_text


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = (*generate(), dom_declarations())
    for name, text in zip(
        ("contracts.d.ts", "contract_schemas.js", "dom_types.d.ts"), generated, strict=True
    ):
        path = ASSETS / name
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                raise SystemExit(f"{path.name} is stale; run tools/generate_web_contracts.py")
        else:
            path.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
